on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push (main)
jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop

      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'laravel' # Optional, default value is "test". The specified database which will be create
          mysql root password: password # Required if "mysql user" is empty, default is empty. The root superuser password
          mysql user: root # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: password # Required if "mysql user" exists. The password for the "mysql user"
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      # - name: Install dependencies composer
      #   run: composer install --prefer-dist --no-progress
      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan migrate
          php artisan key:generate

      - name: Run tests
        run: php artisan test tests/Feature/AuthTest.php
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@master
        with:
          server: ftp.codetify.tech
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /public_html/kapo-api/
